name: google_maps_routes
description: A package for drawing routes on Google Maps by using the Google Directions API.
version: 1.1.2
homepage: https://github.com/aikenahac/google_maps_routes#readme

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_polyline_points:
    git:
      url: https://github.com/hamza39460/flutter_polyline_points.git
      ref: master # branch name
  google_maps_flutter: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
